#!/bin/python3
from turtle import *
from random import randint
import time

speed(0)
penup()
goto(-140, 140)

for step in range(15):
    write(step, align='center')
    right(90)
    for line in range(10):
        forward(10)
        pendown()
        forward(10)
        penup()
    backward(200)
    left(90)
    forward(20)

ada = Turtle()
ada.color('red')
ada.shape('turtle')

ada.penup()
ada.goto(-160, 100)
ada.right(360)
ada.pendown()

bob = Turtle()
bob.color('blue')
bob.shape('turtle')

bob.penup()
bob.goto(-160, 70)
bob.right(360)
bob.pendown()

John = Turtle()
John.color('dark gray')
John.shape('turtle')

John.penup()
John.goto(-160, 40)
John.right(360)
John.pendown()

Jenn = Turtle()
Jenn.color('hot pink')
Jenn.shape('turtle')

Jenn.penup()
Jenn.goto(-160, 10)
Jenn.right(360)
Jenn.pendown()

time.sleep(10)

for turn in range(100):
    ada.forward(randint(1, 5))
    bob.forward(randint(1, 5))
    John.forward(randint(1, 5))
    Jenn.forward(randint(1, 5))

exitonclick()